/** Editorial and static content. Kept apart from market data so it can move to a CMS without touching providers. */

export const LEARN: { slug: string; section: string; title: string; summary: string; body: string[] }[] = [
  { slug: 'what-is-a-stock', section: 'Investing basics', title: 'What a share of stock is', summary: 'Ownership, price and why the two are different things.', body: ['A share is a fractional claim on a company: its assets, its earnings and a vote on how it is run. The share price is what the last buyer paid, which reflects expectations about the future more than a tally of what the company owns today.', 'Market capitalisation is price multiplied by shares outstanding. It lets you compare the size of companies that have very different share prices.'] },
  { slug: 'etf-basics', section: 'ETFs', title: 'How an ETF works', summary: 'A fund that trades like a share and usually tracks an index.', body: ['An exchange-traded fund pools money to hold a basket of securities and issues shares that trade on an exchange through the day. Most track an index, so their job is to match it at low cost rather than beat it.', 'Three numbers do most of the work when you read an ETF: the expense ratio (what you pay each year), assets under management (how large it is) and tracking difference (how far its return lags the index).'] },
  { slug: 'reading-valuation', section: 'Fundamental analysis', title: 'Reading valuation multiples', summary: 'P/E, forward P/E, P/B and EV/EBITDA, and what each compares.', body: ['A multiple divides price by something the business produces. Price to earnings compares price with profit per share; forward P/E uses expected profit; price to book compares price with accounting net assets; EV/EBITDA compares the value of the whole firm, debt included, with operating cash earnings.', 'Multiples only mean something next to a comparison: the company’s own history, its sector, or its growth rate. A high multiple on fast growth can be cheaper than a low multiple on shrinking profits.'] },
  { slug: 'technical-indicators', section: 'Technical analysis', title: 'Moving averages and RSI', summary: 'What trend and momentum indicators measure, and what they do not.', body: ['A moving average smooths price over a window, such as 50 or 200 days, to show direction. Price above both averages is commonly read as an uptrend. The relative strength index measures the balance of recent gains and losses on a 0 to 100 scale; readings above 70 or below 30 mark unusually strong or weak stretches.', 'Indicators summarise what price has already done. They describe conditions and do not predict outcomes.'] },
  { slug: 'understanding-risk', section: 'Risk', title: 'Volatility, beta and drawdown', summary: 'Three ways to describe how rough the ride has been.', body: ['Volatility measures how widely returns vary. Beta measures how much an asset has tended to move when its home index moves: 1.0 means in step, above 1.0 means more. Maximum drawdown is the largest peak-to-trough fall over a period.', 'Each answers a different question, so read them together. A low-beta asset can still suffer a deep drawdown.'] },
  { slug: 'global-markets-from-india', section: 'Global markets', title: 'Following global markets from India', summary: 'Sessions, time zones and why IST matters.', body: ['Markets open in sequence around the world. On a typical day in India, Asian markets trade through the morning, Europe opens after midday and the United States opens in the evening, close to 19:00 or 20:00 IST depending on daylight saving time.', 'INRGIFT shows every session on an IST axis so you can see what is open now and what opens next without converting time zones.'] },
  { slug: 'currency-and-returns', section: 'Currencies', title: 'How currency changes your return', summary: 'The asset return and the exchange rate both count.', body: ['If a US share rises 10% and the dollar rises 3% against the rupee, a rupee-based holder’s return is about 13.3%. If the dollar falls instead, part of the gain is lost.', 'This is why INRGIFT shows approximate INR values and the reference USD/INR rate beside foreign assets.'] },
  { slug: 'gift-city', section: 'Global markets', title: 'What GIFT City is', summary: 'India’s international financial services centre in Gujarat.', body: ['Gujarat International Finance Tec-City hosts an International Financial Services Centre where exchanges such as NSE IX operate in foreign currency for long hours. GIFT Nifty, a futures contract on the NIFTY 50, trades there and is widely watched as an early indication for the Indian market.', 'INRGIFT lists NSE IX among India’s venues and shows GIFT Nifty alongside the domestic indices.'] },
];

export const GLOSSARY: { term: string; definition: string; formula?: string; why: string; related: string[] }[] = [
  { term: 'Assets under management (AUM)', definition: 'The total market value of everything a fund holds.', why: 'Larger funds tend to trade with tighter spreads and are less likely to close.', related: ['Expense ratio', 'ETF'] },
  { term: 'Beta', definition: 'How much an asset has moved relative to a benchmark index.', formula: 'Covariance(asset, index) ÷ Variance(index)', why: 'Shows whether an asset has amplified or dampened market moves.', related: ['Volatility', 'Maximum drawdown'] },
  { term: 'Dividend yield', definition: 'Annual dividends per share as a percentage of the share price.', formula: 'Annual dividend per share ÷ Price × 100', why: 'Lets you compare income across assets with different prices.', related: ['Ex-dividend date'] },
  { term: 'Duration', definition: 'A bond’s sensitivity to interest-rate changes, in years.', why: 'A bond with a duration of 8 falls roughly 8% in price if yields rise one percentage point.', related: ['Yield to maturity', 'Coupon'] },
  { term: 'ETF', definition: 'An exchange-traded fund: a pooled fund whose shares trade on an exchange.', why: 'Offers diversified exposure in one instrument, usually at low cost.', related: ['Expense ratio', 'Tracking difference'] },
  { term: 'EV / EBITDA', definition: 'Enterprise value divided by earnings before interest, tax, depreciation and amortisation.', formula: '(Market cap + Debt − Cash) ÷ EBITDA', why: 'Compares companies with different debt levels on a like-for-like basis.', related: ['P/E ratio'] },
  { term: 'Ex-dividend date', definition: 'The first day a share trades without the right to the next dividend.', why: 'You must own the share before this date to receive the payment.', related: ['Dividend yield'] },
  { term: 'Expense ratio', definition: 'The annual cost of a fund as a percentage of assets.', why: 'Costs compound: a small difference becomes large over many years.', related: ['ETF', 'Tracking difference'] },
  { term: 'FFO', definition: 'Funds from operations: a REIT’s net income with property depreciation added back.', formula: 'Net income + Depreciation − Gains on property sales', why: 'A better measure of a REIT’s recurring cash earnings than net income.', related: ['REIT'] },
  { term: 'Market capitalisation', definition: 'The total market value of a company’s shares.', formula: 'Share price × Shares outstanding', why: 'The standard measure of company size.', related: ['P/E ratio'] },
  { term: 'Maximum drawdown', definition: 'The largest peak-to-trough fall over a period.', why: 'Shows the worst loss a holder would have sat through.', related: ['Volatility', 'Beta'] },
  { term: 'P/E ratio', definition: 'Share price divided by earnings per share.', formula: 'Price ÷ Earnings per share', why: 'Shows how much the market pays for each unit of profit.', related: ['EV / EBITDA', 'Market capitalisation'] },
  { term: 'REIT', definition: 'A real estate investment trust: a company that owns income-producing property and distributes most of its income.', why: 'Gives listed, liquid exposure to property.', related: ['FFO', 'Dividend yield'] },
  { term: 'ROIC', definition: 'Return on invested capital: operating profit after tax relative to the capital used to earn it.', formula: 'NOPAT ÷ (Debt + Equity)', why: 'Shows how efficiently a business turns capital into profit.', related: ['P/E ratio'] },
  { term: 'RSI', definition: 'Relative strength index: a 0 to 100 momentum measure based on recent gains and losses.', why: 'Flags unusually strong or weak recent price action.', related: ['Volatility'] },
  { term: 'Tracking difference', definition: 'The gap between a fund’s return and its index’s return.', why: 'The real cost of holding an index fund, after fees and frictions.', related: ['Expense ratio', 'ETF'] },
  { term: 'Volatility', definition: 'How widely an asset’s returns vary, usually annualised standard deviation.', why: 'A common measure of how uncertain returns have been.', related: ['Beta', 'Maximum drawdown'] },
  { term: 'Yield to maturity', definition: 'The annual return on a bond if held to maturity and all payments are made.', why: 'Lets you compare bonds with different prices and coupons.', related: ['Duration', 'Coupon'] },
];

export const FAQ: { category: string; q: string; a: string }[] = [
  { category: 'Account', q: 'Do I need an account to use INRGIFT?', a: 'No. Markets, assets, the screener, compare and research are open. An account adds watchlists, alerts, saved screens, saved comparisons and notes.' },
  { category: 'Account', q: 'Why do you ask for a phone number and an authenticator app?', a: 'Your saved research is private. Verifying a phone and enrolling an authenticator protects the account if a password leaks.' },
  { category: 'Data', q: 'Are the prices real?', a: 'This build runs on a demo data provider. Values are realistic but are not current market prices. Each module shows a data status and a timestamp, and a Demo data label appears while the demo provider is active.' },
  { category: 'Data', q: 'What do Live, Delayed and End of day mean?', a: 'They describe freshness. Live is within seconds of the exchange, Delayed is typically 15 minutes behind, End of day is the official close. The full list is on the Data and methodology page.' },
  { category: 'Markets', q: 'Which markets are covered?', a: 'The markets directory lists every covered market with its exchanges, currency, hours in IST and data status. Coverage comes from configuration, so the list grows as data sources are added.' },
  { category: 'Assets', q: 'Why do some metrics show a dash or n/a?', a: 'A dash means the source has no value for that metric. n/a means the metric does not apply to that kind of asset, such as a P/E ratio for a gold fund. INRGIFT does not fill gaps with zeros.' },
  { category: 'Research', q: 'Does INRGIFT tell me what to buy?', a: 'No. Research describes data and context. There are no buy or sell ratings and no price targets.' },
  { category: 'Research', q: 'Can I trade through INRGIFT?', a: 'No. INRGIFT is a research and information platform. It is not a broker and it does not place orders or hold funds.' },
  { category: 'Security', q: 'Who can see my watchlists and notes?', a: 'Only you. Private data is stored with row-level security so each row is readable only by the account that owns it.' },
  { category: 'Pricing', q: 'What does INRGIFT cost?', a: 'It is free today. Paid plans for deeper data and research are planned and will be listed on the pricing page before they launch.' },
];

export const PLANS = [
  { name: 'Free', price: '₹0', status: 'Available now', features: ['Global markets, heatmap and movers', 'Stock and ETF research pages', 'Screener and four-way compare', 'One watchlist, alerts and notes', 'Delayed and end-of-day data'] },
  { name: 'Pro', price: 'To be announced', status: 'Planned', features: ['Everything in Free', 'Multiple watchlists and more alerts', 'Screener export and saved-screen history', 'Deeper fundamentals history', 'Real-time data where licensed'] },
  { name: 'Enterprise', price: 'Contact us', status: 'Planned', features: ['Everything in Pro', 'Team workspaces and shared collections', 'Data delivery options', 'Priority support'] },
];

const REVIEW = 'This text is a working draft included so the page is complete in development. It has not been reviewed by a lawyer and must be replaced with reviewed terms before launch.';
export const LEGAL: Record<string, { title: string; sections: [string, string][] }> = {
  privacy: { title: 'Privacy Policy', sections: [['Status', REVIEW], ['What we collect', 'Account details you provide (name, email, phone), preferences you set, and the watchlists, alerts, screens, comparisons and notes you save.'], ['How we use it', 'To run your account, show your saved research, send the alerts you create and keep the service secure. We do not sell personal data.'], ['Where it is stored', 'Private data is stored in a managed database with row-level security, so each record is readable only by its owner.'], ['Your choices', 'You can edit your profile, delete saved items, and ask for your account and data to be deleted through the contact page.']] },
  terms: { title: 'Terms of Use', sections: [['Status', REVIEW], ['The service', 'INRGIFT provides market information and research tools. It is not a broker, does not execute transactions and does not provide investment advice.'], ['Your account', 'You are responsible for keeping your credentials secure and for activity under your account.'], ['Acceptable use', 'Do not scrape, resell or redistribute data, attempt to bypass access controls, or interfere with the service.'], ['Data', 'Market data may be delayed, incomplete or unavailable. Status and timestamps are shown with each module.']] },
  cookies: { title: 'Cookie Policy', sections: [['Status', REVIEW], ['Essential cookies', 'Used to keep you signed in and to protect your session. The service does not work without them.'], ['Preferences', 'Your display currency and similar settings are kept in your browser so they persist between visits.'], ['Analytics', 'No third-party advertising cookies are set by this build.']] },
  'risk-disclosure': { title: 'Risk Disclosure', sections: [['Status', REVIEW], ['Information only', 'Content on INRGIFT is for information and research. It is not a recommendation to transact in any security and does not consider your circumstances.'], ['Market risk', 'The value of investments can fall as well as rise. Past performance does not indicate future results.'], ['Currency risk', 'Returns on foreign assets depend on exchange rates as well as asset prices. INR values shown are approximate.'], ['Data risk', 'Data can be delayed or wrong. Verify important figures with the issuer or exchange before relying on them.']] },
  refund: { title: 'Refund Policy', sections: [['Status', REVIEW], ['Current plans', 'INRGIFT is free today, so there are no charges to refund.'], ['Future paid plans', 'Refund terms for paid plans will be published here before those plans are sold.']] },
  grievance: { title: 'Grievance Redressal', sections: [['Status', REVIEW], ['Raising a concern', 'Use the contact page and choose the Support category. Include your account email and a description of the issue.'], ['What happens next', 'A named grievance officer, response timelines and an escalation path will be published here before launch.']] },
};
