/**
 * Editorial and static content. Kept apart from market data so it can move to a CMS without touching providers.
 * Pages read content only through the async getters at the bottom of this file; swapping the arrays for CMS
 * queries changes nothing else. Shapes are the CMS content models.
 */

// Learn articles and glossary terms live in ./content/* with a CMS-ready model (status, author, reviewer, dates).
import { GLOSSARY_TERMS } from './content/glossary';
import { LEARN_ARTICLES } from './content/learn';
import { LEARN_GUIDES } from './content/learn-guides';
import { PUBLISHED_ONLY, type GlossaryTerm, type LearnArticle } from './content/types';
export type { ContentStatus, ContentType, GlossaryTerm, LearnArticle, LearnSection } from './content/types';

export const FAQ: { category: string; q: string; a: string }[] = [
  { category: 'Account', q: 'Do I need an account to use INRGIFT?', a: 'No. Markets, assets, the screener, compare and research are open. An account adds watchlists, alerts, saved screens, saved comparisons and notes.' },
  { category: 'Account', q: 'Why do you ask for a phone number and an authenticator app?', a: 'Your saved research is private. Verifying a phone and enrolling an authenticator protects the account if a password leaks.' },
  { category: 'Data', q: 'Are the prices real?', a: 'This build runs on a demo data provider. Values are realistic but are not current market prices. Each module shows a data status and a timestamp, and a Demo data label appears while the demo provider is active.' },
  { category: 'Data', q: 'What do Live, Delayed and End of day mean?', a: 'They describe freshness. Live is within seconds of the exchange, Delayed is typically 15 minutes behind, End of day is the official close. The full list is on the Data and methodology page.' },
  { category: 'Markets', q: 'Which markets are covered?', a: 'The markets directory lists every covered market with its exchanges, currency, hours in IST and data status. Coverage comes from configuration, so the list grows as data sources are added.' },
  { category: 'Assets', q: 'Why do some metrics show a dash or n/a?', a: 'A dash means the source has no value for that metric. n/a means the metric does not apply to that kind of asset, such as a P/E ratio for a gold fund. INRGIFT does not fill gaps with zeros.' },
  { category: 'Research', q: 'Does INRGIFT make recommendations?', a: 'No. Research describes data and context. There are no ratings, no price targets and no personal recommendations.' },
  { category: 'Research', q: 'Is INRGIFT a broker?', a: 'No. INRGIFT is a research and information platform. It does not hold funds or act on your behalf, and it is not an investment adviser.' },
  { category: 'Security', q: 'Who can see my watchlists and notes?', a: 'Only you. Private data is stored with row-level security so each row is readable only by the account that owns it.' },
  { category: 'Pricing', q: 'What does INRGIFT cost?', a: 'It is free today. Paid plans for deeper data and research are planned and will be listed on the pricing page before they launch.' },
];

export const PLANS = [
  { name: 'Free', price: '₹0', status: 'Available now', features: ['Global markets, heatmap and movers', 'Stock and ETF research pages', 'Screener and four-way compare', 'One watchlist, alerts and notes', 'Delayed and end-of-day data'] },
  { name: 'Pro', price: 'To be announced', status: 'Planned', features: ['Everything in Free', 'Multiple watchlists and more alerts', 'Screener export and saved-screen history', 'Deeper fundamentals history', 'Real-time data where licensed'] },
  { name: 'Enterprise', price: 'Contact us', status: 'Planned', features: ['Everything in Pro', 'Team workspaces and shared collections', 'Data delivery options', 'Priority support'] },
];

const REVIEW = 'This text is a working draft included so the page is complete in development. It has not been reviewed by a lawyer and must be replaced with reviewed terms before launch.';
export const LEGAL: Record<string, { title: string; sections: [string, string][] }> = {
  privacy: { title: 'Privacy Policy', sections: [['Status', REVIEW], ['What we collect', 'Account details you provide (name, email, phone), preferences you set, and the watchlists, alerts, screens, comparisons and notes you save.'], ['How we use it', 'To run your account, show your saved research, send the alerts you create and keep the service secure. We do not sell personal data.'], ['Where it is stored', 'Private data is stored in a managed database with row-level security, so each record is readable only by its owner.'], ['Your choices', 'You can edit your profile, delete saved items, and ask for your account and data to be deleted through the contact page.']] },
  terms: { title: 'Terms of Use', sections: [['Status', REVIEW], ['The service', 'INRGIFT provides market information and research tools. It is not a broker and does not provide investment advice.'], ['Your account', 'You are responsible for keeping your credentials secure and for activity under your account.'], ['Acceptable use', 'Do not scrape, resell or redistribute data, attempt to bypass access controls, or interfere with the service.'], ['Data', 'Market data may be delayed, incomplete or unavailable. Status and timestamps are shown with each module.']] },
  cookies: { title: 'Cookie Policy', sections: [['Status', REVIEW], ['Essential cookies', 'Used to keep you signed in and to protect your session. The service does not work without them.'], ['Preferences', 'Your display currency and similar settings are kept in your browser so they persist between visits.'], ['Analytics', 'No third-party advertising cookies are set by this build.']] },
  'risk-disclosure': { title: 'Risk Disclosure', sections: [['Status', REVIEW], ['Information only', 'Content on INRGIFT is for information and research. It is not a recommendation to transact in any security and does not consider your circumstances.'], ['Market risk', 'The value of investments can fall as well as rise. Past performance does not indicate future results.'], ['Currency risk', 'Returns on foreign assets depend on exchange rates as well as asset prices. INR values shown are approximate.'], ['Data risk', 'Data can be delayed or wrong. Verify important figures with the issuer or exchange before relying on them.']] },
  refund: { title: 'Refund Policy', sections: [['Status', REVIEW], ['Current plans', 'INRGIFT is free today, so there are no charges to refund.'], ['Future paid plans', 'Refund terms for paid plans will be published here before those plans are sold.']] },
  grievance: { title: 'Grievance Redressal', sections: [['Status', REVIEW], ['Raising a concern', 'Use the contact page and choose the Support category. Include your account email and a description of the issue.'], ['What happens next', 'A named grievance officer, response timelines and an escalation path will be published here before launch.']] },
};


/**
 * Product tutorials. Each is a real screen recording of INRGIFT (demo data, labelled on screen) with WebVTT captions,
 * a transcript and chapters. `placements` decide where a video appears: `learn:<slug>` or `page:<key>`.
 * A CMS can supply the same shape; `src` may be omitted for a transcript-only entry.
 */
export interface VideoItem { id: string; title: string; summary: string; durationSeconds: number; src?: string; type?: string; poster: string; captions?: string; transcript: string[]; chapters: [number, string][]; placements: string[]; recordedAt: string }
/** Tutorials recorded from the running product by scripts/record-tutorials.mjs (demo data). Re-run it after UI changes. */
export const VIDEOS: VideoItem[] = [
  { id: "product-walkthrough", title: "A tour of INRGIFT", summary: "A two-minute map of INRGIFT: markets, heatmap, screener, compare and research.", durationSeconds: 41, src: '/media/product-walkthrough.webm', type: 'video/webm', poster: '/media/product-walkthrough.jpg', captions: '/media/product-walkthrough.en.vtt', transcript: ["INRGIFT is a research view of global markets, built from India.", "Trading sessions are shown on India time, with each market’s status.", "Markets lists every covered exchange with its session and index.", "The global heatmap sizes assets by value and colours them by change.", "The screener filters stocks, ETFs and REITs on more than thirty metrics.", "Compare puts up to four assets side by side on one rebased chart.", "Research notes describe the data, with sources, limitations and method."], chapters: [[0, "INRGIFT is a research view of global markets"], [4.8, "Trading sessions are shown on India time"], [9.7, "Markets lists every covered exchange with its se"], [14.2, "The global heatmap sizes assets by value and col"], [19.3, "The screener filters stocks"], [30.5, "Compare puts up to four assets side by side on o"], [36, "Research notes describe the data"]], placements: ["page:support", "page:resources", "page:about"], recordedAt: '2026-10-06' },
  { id: "research-an-asset", title: "Research any asset in a minute", summary: "Search, open the research page, read the chart and its data status, then scroll to valuation, peers and identity.", durationSeconds: 28, src: '/media/research-an-asset.webm', type: 'video/webm', poster: '/media/research-an-asset.jpg', captions: '/media/research-an-asset.en.vtt', transcript: ["Start anywhere: press / to open universal search.", "Type a ticker or a name. Results are grouped by asset class.", "Enter opens the research page.", "Every module shows its data status and an exact time in IST.", "Change the period, and read any point with the crosshair.", "Scroll for valuation, fundamentals, peers and identity."], chapters: [[0, "Start anywhere"], [3.8, "Type a ticker or a name"], [9, "Enter opens the research page"], [11.9, "Every module shows its data status and an exact "], [17, "Change the period"], [21.5, "Scroll for valuation"]], placements: ["learn:what-is-a-stock", "learn:reading-valuation", "page:support"], recordedAt: '2026-10-06' },
  { id: "heatmap-drill-down", title: "Read the global heatmap", summary: "Size, colour metric, period and drill-down: go from the whole world to one company.", durationSeconds: 28, src: '/media/heatmap-drill-down.webm', type: 'video/webm', poster: '/media/heatmap-drill-down.jpg', captions: '/media/heatmap-drill-down.en.vtt', transcript: ["Tiles are sized by market value and coloured by the change you choose.", "Switch the period to one month to see the trend instead of today.", "Select a region header to drill down a level.", "Then a country, then a sector.", "Select a tile for a quick view with price, returns and actions.", "The breadcrumb takes you back to the global view."], chapters: [[0, "Tiles are sized by market value and coloured by "], [5.5, "Switch the period to one month to see the trend "], [11, "Select a region header to drill down a level"], [15.2, "Then a country"], [18.3, "Select a tile for a quick view with price"], [23.5, "The breadcrumb takes you back to the global view"]], placements: ["learn:global-markets-from-india", "page:heatmap", "page:support"], recordedAt: '2026-10-06' },
  { id: "build-a-screen", title: "Build and save a screen", summary: "Universe, filters, groups and a shareable link: the screener from first filter to saved screen.", durationSeconds: 31, src: '/media/build-a-screen.webm', type: 'video/webm', poster: '/media/build-a-screen.jpg', captions: '/media/build-a-screen.en.vtt', transcript: ["The screener starts with an example: large companies growing fast or paying a dividend.", "Choose the universe: stocks, ETFs, REITs or all.", "Add a filter. Each one has a field, a condition and a value.", "Results update as you type, with every metric explained.", "Groups combine filters with match all or match any.", "The address bar is always a shareable link. Name the screen and save it to your workspace."], chapters: [[0, "The screener starts with an example"], [5.8, "Choose the universe"], [9.7, "Add a filter"], [15.2, "Results update as you type"], [19.3, "Groups combine filters with match all or match a"], [23.5, "The address bar is always a shareable link"]], placements: ["learn:reading-valuation", "page:screener", "page:support"], recordedAt: '2026-10-06' },
  { id: "etf-review", title: "Review an ETF in eight steps", summary: "Read any ETF the same way: objective and cost, size and liquidity, holdings, allocation, performance and risk.", durationSeconds: 31, src: '/media/etf-review.webm', type: 'video/webm', poster: '/media/etf-review.jpg', captions: '/media/etf-review.en.vtt', transcript: ["The eight-step review reads one ETF the same way every time.", "Objective and cost: what the fund tracks and what it charges each year.", "Size and liquidity: how large the fund is and how much it trades.", "Holdings and allocation: concentration by company, sector and country.", "Performance and risk: returns, volatility and the deepest fall.", "Each step shows its data status. It describes the fund; it does not recommend it."], chapters: [[0, "The eight-step review reads one ETF the same way"], [4.8, "Objective and cost"], [10.3, "Size and liquidity"], [15.8, "Holdings and allocation"], [20, "Performance and risk"], [24.2, "Each step shows its data status"]], placements: ["learn:etf-basics", "page:etf-review"], recordedAt: '2026-10-06' },
  { id: "market-hours", title: "Market hours on India time", summary: "Every exchange's hours converted to India time, with live session status and holidays.", durationSeconds: 25, src: '/media/market-hours.webm', type: 'video/webm', poster: '/media/market-hours.jpg', captions: '/media/market-hours.en.vtt', transcript: ["Every exchange’s regular hours, converted to India Standard Time.", "Blue bars are open now; the saffron line marks the current time in IST.", "Status comes from each exchange’s calendar: holidays and early closes included.", "Open a market for its hours, today’s status, index and covered listings.", "Prices carry the same status and timestamp everywhere they appear."], chapters: [[0, "Every exchange’s regular hours"], [4.2, "Blue bars are open now"], [10, "Status comes from each exchange’s calendar"], [14.8, "Open a market for its hours"], [20, "Prices carry the same status and timestamp every"]], placements: ["learn:global-markets-from-india", "page:markets"], recordedAt: '2026-10-06' },
  { id: "methodology", title: "How to read data status and methodology", summary: "What each data status means, where the data comes from, and why INRGIFT never fills gaps with zeros.", durationSeconds: 31, src: '/media/methodology.webm', type: 'video/webm', poster: '/media/methodology.jpg', captions: '/media/methodology.en.vtt', transcript: ["Every number on INRGIFT carries a status and an exact timestamp.", "Live, delayed, end of day, closed, unavailable, stale and error each have their own badge and glyph.", "The page names the current data source and how the data flows.", "A dash means the source has no value; n/a means the metric does not apply. Nothing is filled with zeros.", "Research describes data. It carries no ratings, no price targets and no advice."], chapters: [[0, "Every number on INRGIFT carries a status and an "], [4.8, "Live"], [11.6, "The page names the current data source and how t"], [16.8, "A dash means the source has no value"], [24.6, "Research describes data"]], placements: ["page:data", "page:support"], recordedAt: '2026-10-06' },
];

/* ------------------------------- Content access (CMS seam) ------------------------------- */
export type FaqItem = (typeof FAQ)[number];
export type LegalDoc = { slug: string; title: string; sections: [string, string][] };
const LEARN_ALL: LearnArticle[] = [...LEARN_ARTICLES, ...LEARN_GUIDES].filter((a) => PUBLISHED_ONLY(a.status));
const TERMS: GlossaryTerm[] = GLOSSARY_TERMS.filter((t) => PUBLISHED_ONLY(t.status));
const names = (t: GlossaryTerm) => [t.term.replace(/ \(.*\)$/, ''), ...(t.aliases ?? [])];
/** Plain text of an article, for reading time, glossary detection and search. */
export const articleText = (a: LearnArticle) => [a.title, a.summary, ...a.keyPoints, ...a.sections.flatMap((s) => [s.heading, ...s.paragraphs, ...(s.list ?? []), s.example ?? ''])].join(' ');

export async function getLearnArticles(): Promise<LearnArticle[]> { return LEARN_ALL; }
export async function getLearnArticle(slug: string): Promise<LearnArticle | null> { return LEARN_ALL.find((a) => a.slug === slug) ?? null; }
export async function getGlossary(): Promise<GlossaryTerm[]> { return [...TERMS].sort((a, b) => a.term.localeCompare(b.term)); }
export async function getTerm(slug: string): Promise<GlossaryTerm | null> { return TERMS.find((t) => t.slug === slug) ?? null; }
/** Glossary terms whose name or alias appears as a whole word in a piece of text, for internal linking. */
export async function termsMentionedIn(text: string, limit = 6): Promise<GlossaryTerm[]> {
  const t = ` ${text.toLowerCase()} `;
  const esc = (s: string) => s.toLowerCase().replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');
  return TERMS.filter((x) => names(x).some((n) => new RegExp(`[^a-z0-9]${esc(n)}[^a-z0-9]`).test(t))).slice(0, limit);
}
/** Slug for a term name or alias. */
export const termSlug = (name: string) => TERMS.find((t) => names(t).some((n) => n.toLowerCase() === name.toLowerCase()) || t.term === name)?.slug ?? name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
export async function getFaq(): Promise<FaqItem[]> { return FAQ; }
export async function getPlans() { return PLANS; }
export async function getLegalDocs(): Promise<LegalDoc[]> { return Object.entries(LEGAL).map(([slug, d]) => ({ slug, ...d })); }
export async function getLegalDoc(slug: string): Promise<LegalDoc | null> { const d = LEGAL[slug]; return d ? { slug, ...d } : null; }
export async function getVideos(): Promise<VideoItem[]> { return VIDEOS; }
export async function getVideoFor(placement: string): Promise<VideoItem | null> { return VIDEOS.find((v) => v.placements.includes(placement)) ?? null; }
